server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.86.111:8848
    gateway:
      discovery:
        locator:
          enabled: false
      enabled: true
  profiles:
    active: filterfacotry


















management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



